version: '3.4'

services: 
  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"
    volumes:
    - .:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
    - "8080:80"
    volumes:
    - .:/app
