version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    tmpfs:
      - /tmp
  backend: &backend
    <<: *app
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
  web:
    <<: *backend
    command: bash -c "bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - frontend
